import os

from conan import ConanFile
from conan.tools.build import check_min_cppstd, cross_building
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.env import VirtualBuildEnv, VirtualRunEnv
from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, replace_in_file, rmdir
from conan.tools.microsoft import check_min_vs, is_msvc
from conan.tools.scm import Version
from conan.errors import ConanInvalidConfiguration

# Load the generated component dependency information.
#
# `google-cloud-cpp` has well over 200 components. Conan cannot use the CMake
# files generated by `google-cloud-cpp`. Manually maintaining this dependency
# information is error prone and fairly tedious. A helper script in this
# directory reproduces the algorithms used by `google-cloud-cpp` to generate its
# dependency information. With each new revision of `google-cloud-cpp` the
# script will be used to generate a new file with the component dependency
# information. The expectation is that maintaining this script will be easier
# than writing long lists of dependencies by hand.
import components_2_28_0

required_conan_version = ">=1.56.0"


class GoogleCloudCppConan(ConanFile):
    name = "google-cloud-cpp"
    description = "C++ Client Libraries for Google Cloud Services"
    license = "Apache-2.0"
    topics = (
        "google",
        "cloud",
        "google-cloud-storage",
        "google-cloud-platform",
        "google-cloud-pubsub",
        "google-cloud-spanner",
        "google-cloud-bigtable",
    )
    homepage = "https://github.com/googleapis/google-cloud-cpp"
    url = "https://github.com/conan-io/conan-center-index"
    package_type = "library"
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    exports = ["components_2_28_0.py"]

    short_paths = True

    # Some components require custom dependency definitions.
    _REQUIRES_CUSTOM_DEPENDENCIES = {
        "bigquery", "bigtable", "iam", "oauth2", "pubsub", "spanner", "storage",
    }

    @property
    def _is_legacy_one_profile(self):
        return not hasattr(self, "settings_build")

    def export_sources(self):
        export_conandata_patches(self)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")
            self.options["protobuf"].shared = True
            self.options["grpc"].shared = True

    def validate(self):
        check_min_vs(self, "192")
        if is_msvc(self) and self.info.options.shared:
            raise ConanInvalidConfiguration(f"{self.ref} shared not supported by Visual Studio")

        if hasattr(self, "settings_build") and cross_building(self):
            raise ConanInvalidConfiguration(
                "Recipe not prepared for cross-building (yet)"
            )

        if (
            self.settings.compiler == "clang"
            and Version(self.settings.compiler.version) < "6.0"
        ):
            raise ConanInvalidConfiguration("Clang version must be at least 6.0.")

        if self.settings.compiler.cppstd:
            check_min_cppstd(self, 14)

        if (
            self.settings.compiler == "gcc"
            and Version(self.settings.compiler.version) < "5.4"
        ):
            raise ConanInvalidConfiguration("Building requires GCC >= 5.4")

        if self.info.options.shared and \
           (not self.dependencies["protobuf"].options.shared or \
            not self.dependencies["grpc"].options.shared):
            raise ConanInvalidConfiguration(
                "If built as shared, protobuf, and grpc must be shared as well."
                " Please, use `protobuf/*:shared=True`, and `grpc/*:shared=True`.")

    def layout(self):
        cmake_layout(self, src_folder="src")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], destination=self.source_folder, strip_root=True)

    def requirements(self):
        # Pinned to match Milvus core dependencies
        self.requires("protobuf/3.21.4", transitive_headers=True)
        self.requires("abseil/20230125.3", transitive_headers=True)
        self.requires("grpc/1.50.1@milvus/dev", transitive_headers=True)
        self.requires("nlohmann_json/3.11.3")
        self.requires("crc32c/1.1.2")
        # The rest require less pinning.
        self.requires("libcurl/[>=7.78 <9]")
        self.requires("openssl/[>=1.1 <4]")
        self.requires("zlib/[>=1.2.11 <2]")

    def build_requirements(self):
        # For the `grpc-cpp-plugin` executable, and indirectly `protoc`
        if not self._is_legacy_one_profile:
            self.tool_requires("grpc/<host_version>")

    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["GOOGLE_CLOUD_CPP_WITH_MOCKS"] = False
        tc.variables["GOOGLE_CLOUD_CPP_ENABLE_MACOS_OPENSSL_CHECK"] = False
        tc.variables["GOOGLE_CLOUD_CPP_ENABLE_WERROR"] = False
        tc.variables["GOOGLE_CLOUD_CPP_ENABLE"] = ",".join(self._components())
        tc.generate()
        VirtualBuildEnv(self).generate()
        if self._is_legacy_one_profile:
            VirtualRunEnv(self).generate(scope="build")
        deps = CMakeDeps(self)
        deps.generate()

    def _patch_sources(self):
        apply_conandata_patches(self)
        # This was informed by comments in the grpc port. On macOS `Make` will
        # run commands via `/bin/sh`. `/bin/sh` is subject to System Integrity
        # Protections.  In particular, the system will purge the DYLD_LIBRARY_PATH
        # enviroment variables:
        #     https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html
        settings_build = getattr(self, "settings_build", self.settings)
        if settings_build.os == "Macos":
            replace_in_file(self, os.path.join(self.source_folder, "cmake/CompileProtos.cmake"),
                            "${Protobuf_PROTOC_EXECUTABLE} ARGS",
                            '${CMAKE_COMMAND} -E env "DYLD_LIBRARY_PATH=$ENV{DYLD_LIBRARY_PATH}" ${Protobuf_PROTOC_EXECUTABLE} ARGS')

    def build(self):
        self._patch_sources()
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def _generate_proto_requires(self, component):
        return components_2_28_0.DEPENDENCIES.get(component, [])

    _SKIPPED_COMPONENTS = {
        # Some protos do not compile due to inconvenient system macros clashing
        # with proto enum values. Protobuf can workaround these problems, but
        # the current version in Conan index (protobuf/3.21.4) do not contain
        # the fixes for these cases.
        # TODO - review after protobuf >= 4.23.x
        'asset',
        'channel',
        'storagetransfer',
    }

    def _components(self):
        # Milvus only needs storage and oauth2 components
        return ["iam", "storage", "oauth2"]

    def _proto_components(self):
        result = components_2_28_0.PROTO_COMPONENTS.copy()
        for c in self._SKIPPED_COMPONENTS:
            result.remove(c + '_protos')
        # TODO - these do not build on Android due to conflicts between OS
        # macros and Proto enums. Revisit after Protobuf >= 4.23.x
        if self.settings.os == "Android":
            result.remove('accesscontextmanager_protos')
            result.remove('talent_protos')
        if self.settings.os == "Windows":
            result.remove('securitycenter_protos')
        return result

    def package(self):
        copy(self, "LICENSE", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
        cmake = CMake(self)
        cmake.install()
        rmdir(self, path=os.path.join(self.package_folder, "lib", "cmake"))
        rmdir(self, path=os.path.join(self.package_folder, "lib", "pkgconfig"))

    def _add_proto_component(self, component):
        self.cpp_info.components[component].requires = self._generate_proto_requires(component)
        self.cpp_info.components[component].libs = [f"google_cloud_cpp_{component}"]
        self.cpp_info.components[component].names["pkg_config"] = f"google_cloud_cpp_{component}"

    def _add_grpc_component(self, component, protos, extra=None):
        SHARED_REQUIRES=["grpc_utils", "common", "grpc::grpc++", "grpc::_grpc", "protobuf::libprotobuf", "abseil::absl_memory"]
        self.cpp_info.components[component].requires = (extra or []) + [protos] + SHARED_REQUIRES
        self.cpp_info.components[component].libs = [f"google_cloud_cpp_{component}"]
        self.cpp_info.components[component].names["pkg_config"] = f"google_cloud_cpp_{component}"

    # The compute librar(ies) do not use gRPC, and they have many components
    # with dependencies between them
    def _add_compute_component(self, component, protos):
        SHARED_REQUIRES=["rest_protobuf_internal", "rest_internal", "common"]
        # Common components shared by other compute components
        COMPUTE_COMMON_COMPONENTS = [
            'compute_global_operations',
            'compute_global_organization_operations',
            'compute_region_operations',
            'compute_zone_operations',
        ]
        requires = [protos]
        if component not in COMPUTE_COMMON_COMPONENTS:
            requires = requires + COMPUTE_COMMON_COMPONENTS
        self.cpp_info.components[component].requires = requires + SHARED_REQUIRES
        self.cpp_info.components[component].libs = [f"google_cloud_cpp_{component}"]
        self.cpp_info.components[component].names["pkg_config"] = f"google_cloud_cpp_{component}"

    def package_info(self):
        # Milvus-specific: only declare components we actually built (iam, storage, oauth2)
        # plus all their proto and utility dependencies.
        self.cpp_info.components["common"].requires = ["abseil::absl_any", "abseil::absl_flat_hash_map", "abseil::absl_memory", "abseil::absl_optional", "abseil::absl_time"]
        self.cpp_info.components["common"].libs = ["google_cloud_cpp_common"]
        self.cpp_info.components["common"].names["pkg_config"] = "google_cloud_cpp_common"

        self.cpp_info.components["rest_internal"].requires = ["common", "libcurl::libcurl", "openssl::ssl", "openssl::crypto", "zlib::zlib"]
        self.cpp_info.components["rest_internal"].libs = ["google_cloud_cpp_rest_internal"]
        self.cpp_info.components["rest_internal"].names["pkg_config"] = "google_cloud_cpp_rest_internal"

        # Declare ALL proto components that were actually built.
        # The googleapis cmake build compiles all protos needed by iam/storage/oauth2.
        INSTALLED_PROTO_COMPONENTS = [
            "api_annotations_protos", "api_auth_protos", "api_backend_protos",
            "api_billing_protos", "api_client_protos", "api_config_change_protos",
            "api_consumer_protos", "api_context_protos", "api_control_protos",
            "api_distribution_protos", "api_documentation_protos", "api_endpoint_protos",
            "api_error_reason_protos", "api_field_behavior_protos", "api_field_info_protos",
            "api_httpbody_protos", "api_http_protos", "api_label_protos",
            "api_launch_stage_protos", "api_logging_protos", "api_log_protos",
            "api_metric_protos", "api_monitored_resource_protos", "api_monitoring_protos",
            "api_policy_protos", "api_quota_protos", "api_resource_protos",
            "api_routing_protos", "api_service_protos", "api_source_info_protos",
            "api_system_parameter_protos", "api_usage_protos", "api_visibility_protos",
            "cloud_common_common_protos", "cloud_extended_operations_protos",
            "cloud_orgpolicy_v1_orgpolicy_protos",
            "iam_credentials_v1_common_protos", "iam_credentials_v1_iamcredentials_protos",
            "iam_protos", "iam_v1_iam_policy_protos", "iam_v1_options_protos",
            "iam_v1_policy_protos", "iam_v2_protos",
            "longrunning_operations_protos",
            "rpc_code_protos", "rpc_context_attribute_context_protos",
            "rpc_error_details_protos", "rpc_status_protos",
            "type_calendar_period_protos", "type_color_protos", "type_date_protos",
            "type_datetime_protos", "type_dayofweek_protos", "type_decimal_protos",
            "type_expr_protos", "type_fraction_protos", "type_interval_protos",
            "type_latlng_protos", "type_localized_text_protos", "type_money_protos",
            "type_month_protos", "type_phone_number_protos", "type_postal_address_protos",
            "type_quaternion_protos", "type_timeofday_protos",
        ]
        for component in INSTALLED_PROTO_COMPONENTS:
            self._add_proto_component(component)

        GRPC_UTILS_REQUIRED_PROTOS = [
            "iam_credentials_v1_iamcredentials_protos",
            "iam_v1_policy_protos",
            "longrunning_operations_protos",
            "rpc_error_details_protos",
            "rpc_status_protos",
        ]
        self.cpp_info.components["grpc_utils"].requires = GRPC_UTILS_REQUIRED_PROTOS + ["common", "abseil::absl_function_ref", "abseil::absl_memory", "abseil::absl_time", "grpc::grpc++", "grpc::_grpc"]
        self.cpp_info.components["grpc_utils"].libs = ["google_cloud_cpp_grpc_utils"]
        self.cpp_info.components["grpc_utils"].names["pkg_config"] = "google_cloud_cpp_grpc_utils"

        self.cpp_info.components["rest_protobuf_internal"].requires = ["rest_internal", "grpc_utils", "common"]
        self.cpp_info.components["rest_protobuf_internal"].libs = ["google_cloud_cpp_rest_protobuf_internal"]
        self.cpp_info.components["rest_protobuf_internal"].names["pkg_config"] = "google_cloud_cpp_rest_protobuf_internal"

        # iam component
        self._add_grpc_component("iam", "iam_protos")

        # oauth2 component (REST-only, no gRPC or protos)
        self.cpp_info.components["oauth2"].requires = ["rest_internal", "common", "nlohmann_json::nlohmann_json", "libcurl::libcurl", "openssl::ssl", "openssl::crypto", "zlib::zlib"]
        self.cpp_info.components["oauth2"].libs = ["google_cloud_cpp_oauth2"]
        self.cpp_info.components["oauth2"].names["pkg_config"] = "google_cloud_cpp_oauth2"

        # storage component
        self.cpp_info.components["storage"].requires = ["rest_internal", "common", "nlohmann_json::nlohmann_json", "abseil::absl_memory", "abseil::absl_strings", "abseil::absl_str_format", "abseil::absl_time", "abseil::absl_variant", "crc32c::crc32c", "libcurl::libcurl", "openssl::ssl", "openssl::crypto", "zlib::zlib"]
        self.cpp_info.components["storage"].libs = ["google_cloud_cpp_storage"]
        self.cpp_info.components["storage"].names["pkg_config"] = "google_cloud_cpp_storage"
