versions:
  "1.0.0-5d2aec9":
    folder: all
  "1.0.0-6b16d93":
    folder: all
  "1.0.0-5b3ac69":
    folder: all
  "1.0.0-a3299ca":
    folder: all
  "1.0.0-60a563c":
    folder: all
  "1.0.0-ae43d5c":
    folder: all
  "1.0.0-3039f35":
    folder: all
  "1.0.0-3a5f4d4":
    folder: all
  "1.0.0-835fcd0":
    folder: all
  "1.0.0-4f41e32":
    folder: all
  "1.0.0-45bff01":
    folder: all
  "1.0.0-860f9a7":
    folder: all
